// Auto-generated by sync-photos.js
// Last updated: 2025-08-03T22:57:49.226Z

export default [
  {
    "src": "../public/img/photos/14766da4-d004-49ea-a60f-ca421bc02eef.jpg",
    "alt": "DCIM\\101GOPRO\\GOPR1478.",
    "date": "2016-01-02T14:33:08.000Z",
    "description": "DCIM\\101GOPRO\\GOPR1478.",
    "camera": "GoPro HERO4 Black",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.8",
      "focalLength": "3mm",
      "exposureTime": "1/1590"
    },
    "dimensions": "4000 × 3000"
  },
  {
    "src": "../public/img/photos/2c564501-ffe4-4e58-bb9a-882bc14e7e01.jpg",
    "alt": "DCIM\\100GOPRO\\GOPR0075.",
    "date": "2015-12-29T18:21:01.000Z",
    "description": "DCIM\\100GOPRO\\GOPR0075.",
    "camera": "GoPro HERO4 Black",
    "techDetails": {
      "iso": 400,
      "aperture": "f/2.8",
      "focalLength": "3mm",
      "exposureTime": "1/6"
    },
    "dimensions": "4000 × 3000"
  },
  {
    "src": "../public/img/photos/7aee3052-3917-49a5-8dd1-1de0b9b7bbe4.jpg",
    "alt": "IMG_20151030_152348.jpg",
    "date": "2015-10-30T14:23:51.000Z",
    "location": {
      "lat": 55.6929877777778,
      "lng": 12.5991858333333
    },
    "locationName": "Christianshavn, Capital Region, Denmark",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/112"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/7ba17c6d-dac5-426c-968b-e9fc1b83695b.jpg",
    "alt": "IMG_20151030_144948.jpg",
    "date": "2015-10-30T13:49:50.000Z",
    "location": {
      "lat": 55.6800155555556,
      "lng": 12.5893177777778
    },
    "locationName": "Christianshavn, Capital Region, Denmark",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/298"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/330073c2-9be4-4ec8-8cc8-1f0d4093bee7.jpg",
    "alt": "IMG_20151007_141020.jpg",
    "date": "2015-10-07T12:10:23.000Z",
    "location": {
      "lat": 51.3543388888889,
      "lng": 3.29748305555556
    },
    "locationName": "Knokke, Flanders, Belgium",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/279"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/b3d1d635-8484-4a36-a65f-5098f2766394.jpg",
    "alt": "IMG_20151007_121818.jpg",
    "date": "2015-10-07T10:18:23.000Z",
    "location": {
      "lat": 51.3547741666667,
      "lng": 3.29944472222222
    },
    "locationName": "Knokke, Flanders, Belgium",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/110"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/2c6fa153-1174-499a-ad24-af2884138b54.jpg",
    "alt": "IMG_20151006_171111.jpg",
    "date": "2015-10-06T15:11:14.000Z",
    "location": {
      "lat": 51.3555536111111,
      "lng": 3.29931555555556
    },
    "locationName": "Knokke, Flanders, Belgium",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 121,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/84"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/88da9ba8-2510-4243-81d0-6049032d6b70.jpg",
    "alt": "IMG_20150920_072413.jpg",
    "date": "2015-09-20T06:24:33.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/3610"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/f5291be5-f61b-44f9-aca9-2754330d4625.jpg",
    "alt": "IMG_20150820_195221.jpg",
    "date": "2015-08-20T18:52:25.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/114"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/4b93a218-5940-4490-82bf-f261b854341b.jpg",
    "alt": "IMG_20150820_002727.jpg",
    "date": "2015-08-19T23:27:31.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 774,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/16"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/80165afb-62ea-465a-b524-8078699635a4.jpg",
    "alt": "IMG_20150819_175102.jpg",
    "date": "2015-08-19T16:51:12.000Z",
    "location": {
      "lat": 41.9194952777778,
      "lng": -8.56915861111111
    },
    "locationName": "Paredes de Coura, Viana do Castelo, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/450"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/9ed5334b-9347-4b81-ae7c-6a32c84015c5.jpg",
    "alt": "IMG_20150819_162244.jpg",
    "date": "2015-08-19T15:22:50.000Z",
    "location": {
      "lat": 41.9200427777778,
      "lng": -8.56737611111111
    },
    "locationName": "Paredes de Coura, Viana do Castelo, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/171"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/915505ea-e79d-4ca2-8c75-e0bcac6e5a68.jpg",
    "alt": "PANO_20150802_193940.jpg",
    "date": "2015-08-02T18:41:13.000Z",
    "location": {
      "lat": 41.3729769444444,
      "lng": -7.87876277777778
    },
    "locationName": "Mondim de Basto, Vila Real, Portugal",
    "camera": "LGE Nexus 5",
    "dimensions": "7936 × 1962"
  },
  {
    "src": "../public/img/photos/9b491e8b-223c-4b0a-9cf1-760865171f8a.jpg",
    "alt": "IMG_20150730_195214.jpg",
    "date": "2015-07-30T17:52:17.000Z",
    "location": {
      "lat": 40.5229591666667,
      "lng": -4.71606527777778
    },
    "locationName": "San Juan de la Nava, Castille and León, Spain",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/4464"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/5bded13e-2114-4199-9ac0-4113c4a10b0e.jpg",
    "alt": "IMG_20150730_132724-PANO.jpg",
    "date": "2015-07-30T11:27:27.000Z",
    "location": {
      "lat": 40.4523308333333,
      "lng": -3.68967
    },
    "locationName": "Chamartín, Madrid, Spain",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "focalLength": "3.970000029mm"
    },
    "dimensions": "4119 × 1186"
  },
  {
    "src": "../public/img/photos/5dee2542-a4f7-4e32-8747-c93d7285122a.jpg",
    "alt": "PANO_20150730_132324.jpg",
    "date": "2015-07-30T11:24:22.000Z",
    "location": {
      "lat": 40.4531477777778,
      "lng": -3.68985
    },
    "locationName": "Chamartín, Madrid, Spain",
    "camera": "LGE Nexus 5",
    "dimensions": "6480 × 1870"
  },
  {
    "src": "../public/img/photos/b9ba80d1-3e58-4752-994a-925295ab6603.jpg",
    "alt": "IMG_20150723_115624.jpg",
    "date": "2015-07-23T09:56:27.000Z",
    "location": {
      "lat": 52.5141166666667,
      "lng": 13.3793944444444
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/2101"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/c6bece2c-c1a7-4704-a929-22c35fd34be1.jpg",
    "alt": "IMG_20150722_205204.jpg",
    "date": "2015-07-22T18:52:07.000Z",
    "location": {
      "lat": 52.5153458333333,
      "lng": 13.4068066666667
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/413"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/e7a85a31-b9b4-47e6-9f5e-44b1007fd494.jpg",
    "alt": "IMG_20150722_183101.jpg",
    "date": "2015-07-22T16:31:04.000Z",
    "location": {
      "lat": 52.5194294444444,
      "lng": 13.4067111111111
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1761"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/5716397d-6a3a-4cc0-b1f0-4cb968a87498.jpg",
    "alt": "IMG_20150722_175617.jpg",
    "date": "2015-07-22T15:56:20.000Z",
    "location": {
      "lat": 52.51918,
      "lng": 13.3948527777778
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1610"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/bd8feb86-2870-45da-8f19-8da64a3c019d.jpg",
    "alt": "IMG_20150722_171021.jpg",
    "date": "2015-07-22T15:10:23.000Z",
    "location": {
      "lat": 52.5194772222222,
      "lng": 13.3768466666667
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1351"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/8077e33b-5fcf-4ddc-baf5-afb0b8c04f59.jpg",
    "alt": "IMG_20150722_165728.jpg",
    "date": "2015-07-22T14:57:36.000Z",
    "location": {
      "lat": 52.5163516666667,
      "lng": 13.3786077777778
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/3436"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/3c77c6b2-fcc8-432f-977a-3dcd54fb9f2d.jpg",
    "alt": "IMG_20150722_150349.jpg",
    "date": "2015-07-22T13:03:53.000Z",
    "location": {
      "lat": 52.5102408333333,
      "lng": 13.4039888888889
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 160,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/66"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/6e522ad4-8c4d-418a-bd58-01d5549da87b.jpg",
    "alt": "IMG_20150721_114258.jpg",
    "date": "2015-07-21T09:43:01.000Z",
    "location": {
      "lat": 51.0535172222222,
      "lng": 13.7350291666667
    },
    "locationName": "Dresden, Saxony, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1376"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/62c9dcb9-3563-4cdb-9501-82ef420a3ca5.jpg",
    "alt": "IMG_20150720_135010.jpg",
    "date": "2015-07-20T11:50:14.000Z",
    "location": {
      "lat": 50.940175,
      "lng": 6.95627527777778
    },
    "locationName": "Köln, North Rhine-Westphalia, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1163"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/1dde03c7-c375-48bf-8253-695310b32a3d.jpg",
    "alt": "IMG_20150714_141333.jpg",
    "date": "2015-07-14T12:13:35.000Z",
    "location": {
      "lat": 48.1413644444444,
      "lng": 11.5649769444444
    },
    "locationName": "Munich, Bavaria, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/494"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/5731e077-92b2-43c7-8d19-d0eb8b29c405.jpg",
    "alt": "IMG_20150705_185323.jpg",
    "date": "2015-07-05T17:53:26.000Z",
    "location": {
      "lat": 41.5196263888889,
      "lng": -8.78613305555556
    },
    "locationName": "Apúlia e Fão, Braga, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/432"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/df0d6e50-dd3d-4153-b1ae-dc77466fae19.jpg",
    "alt": "IMG_20150621_190000.jpg",
    "date": "2015-06-21T18:00:09.000Z",
    "location": {
      "lat": 41.6997938888889,
      "lng": -8.03698638888889
    },
    "locationName": "Vieira do Minho, Braga, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1182"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/85871cae-0244-4163-bfd6-7d6866e4a7cc.jpg",
    "alt": "IMG_20150605_022158.jpg",
    "date": "2015-06-05T01:22:19.000Z",
    "location": {
      "lat": 41.1699169444444,
      "lng": -8.68379166666667
    },
    "locationName": "Nevogilde, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/106"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/e20f1f98-059b-4572-a0a3-2878e9461d35.jpg",
    "alt": "IMG_20150603_163155.jpg",
    "date": "2015-06-03T15:31:59.000Z",
    "location": {
      "lat": 40.197385,
      "lng": -8.43537166666667
    },
    "locationName": "Santa Clara, Coimbra, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 285,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/40"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/419a2c42-39f6-4187-8406-92685316bc7d.jpg",
    "alt": "IMG_20150517_162623.jpg",
    "date": "2015-05-17T15:26:23.586Z",
    "location": {
      "lat": 41.2879104444444,
      "lng": -8.61328505555556
    },
    "locationName": "Santa Maria de Avioso, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1050"
    },
    "dimensions": "3264 × 2448"
  },
  {
    "src": "../public/img/photos/1cbe3dff-a200-4dd1-b8ab-30262af432e5.jpg",
    "alt": "IMG_20150201_152021.jpg",
    "date": "2015-02-01T17:20:27.000Z",
    "location": {
      "lat": -22.9687516666667,
      "lng": -43.3874566666667
    },
    "locationName": "Barra da Tijuca, Rio de Janeiro, Brazil",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1351"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/5584edcc-9fea-41e1-af24-81b283d68c30.jpg",
    "alt": "IMG_20150201_133204.jpg",
    "date": "2015-02-01T15:32:04.904Z",
    "location": {
      "lat": -22.9431343055556,
      "lng": -43.1993064722222
    },
    "locationName": "Rio de Janeiro, Rio de Janeiro, Brazil",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/442"
    },
    "dimensions": "1920 × 1080"
  },
  {
    "src": "../public/img/photos/fdc1d28a-9612-4c1d-bb25-c46250f78272.jpg",
    "alt": "IMG_20141128_201854.jpg",
    "date": "2014-11-28T20:18:59.000Z",
    "location": {
      "lat": 41.4967777777778,
      "lng": -8.36370138888889
    },
    "locationName": "Taipas, Braga, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 580,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/21"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/e234dd18-f64f-4183-819c-4f5f52f3fd7c.jpg",
    "alt": "IMG_20141117_141953.jpg",
    "date": "2014-11-17T13:19:56.000Z",
    "location": {
      "lat": 35.9142713888889,
      "lng": 14.4978452777778
    },
    "locationName": "Sliema, Tas-Sliema, Malta",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/635"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/ea719511-d1fe-48d6-b13b-cece0b3d7c10.jpg",
    "alt": "IMG_20140927_162746.jpg",
    "date": "2014-09-27T14:27:51.000Z",
    "location": {
      "lat": 47.8096483333333,
      "lng": 13.0612486111111
    },
    "locationName": "Salzburg, Salzburg, Austria",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/2907"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/67aed6c6-925f-4e54-ad0e-a3b66ca96848.jpg",
    "alt": "IMG_20140824_182738.jpg",
    "date": "2014-08-24T17:27:38.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 101,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1542"
    },
    "dimensions": "3264 × 2448"
  },
  {
    "src": "../public/img/photos/945031e3-d806-41f4-b080-e96dce7e02f6.jpg",
    "alt": "IMG_20140711_153938.jpg",
    "date": "2014-07-11T14:39:42.000Z",
    "location": {
      "lat": 38.7739205555556,
      "lng": -9.09144861111111
    },
    "locationName": "Parque das Nações, Lisbon, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1129"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/2ffb91f5-e0d3-4ea8-906f-33a637c3623b.jpg",
    "alt": "IMG_20140608_015459.jpg",
    "date": "2014-06-08T00:55:11.000Z",
    "location": {
      "lat": 41.1464077777778,
      "lng": -8.61376583333333
    },
    "locationName": "Porto, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 1089,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/10"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/a51dd67f-0cda-4226-bd89-10a1f9270f49.jpg",
    "alt": "IMG_20140604_225740.jpg",
    "date": "2014-06-04T21:57:40.000Z",
    "location": {
      "lat": 41.1442947222222,
      "lng": -8.61847780555556
    },
    "locationName": "Porto, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 1137,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/30"
    },
    "dimensions": "1920 × 1080"
  },
  {
    "src": "../public/img/photos/874c6106-79dd-4a3a-94fc-69bead7dbd33.jpg",
    "alt": "IMG_20140601_185708.jpg",
    "date": "2014-06-01T17:57:08.000Z",
    "location": {
      "lat": 41.1589508055556,
      "lng": -8.65685175
    },
    "locationName": "Pinheiro Manso, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/822"
    },
    "dimensions": "2448 × 3264"
  }
];
