// Auto-generated by sync-photos.js
// Last updated: 2025-08-02T23:15:39.863Z

export default [
  {
    "src": "../public/img/photos/67aed6c6-925f-4e54-ad0e-a3b66ca96848.jpg",
    "alt": "IMG_20140824_182738.jpg",
    "date": "2014-08-24T17:27:38.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 101,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1542"
    },
    "dimensions": "3264 × 2448"
  },
  {
    "src": "../public/img/photos/945031e3-d806-41f4-b080-e96dce7e02f6.jpg",
    "alt": "IMG_20140711_153938.jpg",
    "date": "2014-07-11T14:39:42.000Z",
    "location": {
      "lat": 38.7739205555556,
      "lng": -9.09144861111111
    },
    "locationName": "Parque das Nações, Lisbon, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1129"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/2ffb91f5-e0d3-4ea8-906f-33a637c3623b.jpg",
    "alt": "IMG_20140608_015459.jpg",
    "date": "2014-06-08T00:55:11.000Z",
    "location": {
      "lat": 41.1464077777778,
      "lng": -8.61376583333333
    },
    "locationName": "Porto, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 1089,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/10"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/a51dd67f-0cda-4226-bd89-10a1f9270f49.jpg",
    "alt": "IMG_20140604_225740.jpg",
    "date": "2014-06-04T21:57:40.000Z",
    "location": {
      "lat": 41.1442947222222,
      "lng": -8.61847780555556
    },
    "locationName": "Porto, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 1137,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/30"
    },
    "dimensions": "1920 × 1080"
  },
  {
    "src": "../public/img/photos/874c6106-79dd-4a3a-94fc-69bead7dbd33.jpg",
    "alt": "IMG_20140601_185708.jpg",
    "date": "2014-06-01T17:57:08.000Z",
    "location": {
      "lat": 41.1589508055556,
      "lng": -8.65685175
    },
    "locationName": "Pinheiro Manso, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/822"
    },
    "dimensions": "2448 × 3264"
  }
];
