// Auto-generated by sync-photos.js
// Last updated: 2026-03-01T11:19:01.815Z

export default [
  {
    "src": "../public/img/photos/70121012-4867-4885-8656-83745378f2ca.jpg",
    "alt": "20210823_174939621_iOS.heic",
    "date": "2021-08-23T17:49:40.089Z",
    "location": {
      "lat": 37.0210611111111,
      "lng": -7.96865
    },
    "locationName": "Faro, Faro, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1597"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/8a524185-7c3b-42ed-87c8-28e83a4fd166.jpg",
    "alt": "20210809_152310079_iOS.heic",
    "date": "2021-08-09T15:23:10.509Z",
    "location": {
      "lat": 37.0722472222222,
      "lng": -8.77405277777778
    },
    "locationName": "Senhora da Luz, Faro, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1370"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/adcffe9b-d135-4a6d-adbe-aca8c4867c1d.jpg",
    "alt": "20210809_103000830_iOS.heic",
    "date": "2021-08-09T10:30:01.232Z",
    "location": {
      "lat": 37.0232722222222,
      "lng": -8.99619166666667
    },
    "locationName": "Sagres, Faro, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/888"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/1824be34-633f-4170-96bf-bf3d7cef1a8f.jpg",
    "alt": "20210809_102501693_iOS.heic",
    "date": "2021-08-09T10:25:02.208Z",
    "location": {
      "lat": 37.0232,
      "lng": -8.99586666666667
    },
    "locationName": "Sagres, Faro, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1261"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/adbf2a39-c25d-4990-9bb1-0441e39706f7.jpg",
    "alt": "20210809_102357661_iOS.heic",
    "date": "2021-08-09T10:23:58.298Z",
    "location": {
      "lat": 37.0232694444444,
      "lng": -8.995875
    },
    "locationName": "Sagres, Faro, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1916"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/c8f00e58-6529-4607-b663-05e65e05221a.jpg",
    "alt": "20210806_132316075_iOS.heic",
    "date": "2021-08-06T13:23:16.547Z",
    "location": {
      "lat": 37.5988388888889,
      "lng": -8.818
    },
    "locationName": "Almograve, Beja, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1261"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/0a76ba05-ffa8-4c6a-8e32-259cebaaf95a.jpg",
    "alt": "20210805_115112843_iOS.heic",
    "date": "2021-08-05T11:51:13.252Z",
    "location": {
      "lat": 37.86955,
      "lng": -8.79185277777778
    },
    "locationName": "Porto Covo, Setúbal, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1653"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/6fdec023-9935-4101-b28a-d43111ff2a57.jpg",
    "alt": "20210804_160553237_iOS.heic",
    "date": "2021-08-04T16:05:53.751Z",
    "location": {
      "lat": 38.4464555555556,
      "lng": -8.37886944444444
    },
    "locationName": "Alcácer do Sal, Setúbal, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/2994"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/be451d78-3a06-45db-9306-31e1ac321599.jpg",
    "alt": "20210703_193808435_iOS.heic",
    "date": "2021-07-03T19:38:09.058Z",
    "location": {
      "lat": 39.3671527777778,
      "lng": -9.40249444444444
    },
    "locationName": "Peniche, Leiria, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/11905"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/b20bc9cf-d119-4c7b-91b8-2d71ecc53270.jpg",
    "alt": "20210610_195410898_iOS.heic",
    "date": "2021-06-10T19:54:11.280Z",
    "location": {
      "lat": 41.0991694444444,
      "lng": -8.070925
    },
    "locationName": "Cinfães, Viseu, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/378"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/1eed981f-0273-43e2-8ffc-78657260ee25.jpg",
    "alt": "20210610_192436321_iOS.heic",
    "date": "2021-06-10T19:24:36.739Z",
    "location": {
      "lat": 41.099175,
      "lng": -8.071025
    },
    "locationName": "Cinfães, Viseu, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/146"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/4b558f50-50ca-4b55-b304-41036c2aeb22.jpg",
    "alt": "20210610_192405059_iOS.heic",
    "date": "2021-06-10T19:24:05.459Z",
    "location": {
      "lat": 41.0991222222222,
      "lng": -8.07100555555555
    },
    "locationName": "Cinfães, Viseu, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/400"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/e7ee0912-f81c-4455-a63b-39cdcd6d80e1.jpg",
    "alt": "20210610_182113786_iOS.heic",
    "date": "2021-06-10T18:21:14.402Z",
    "location": {
      "lat": 41.0989,
      "lng": -8.07076388888889
    },
    "locationName": "Cinfães, Viseu, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/564"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/b6a11a68-457f-4961-b01b-548da1f023f5.jpg",
    "alt": "20210113_172919991_iOS.heic",
    "date": "2021-01-13T17:29:20.696Z",
    "location": {
      "lat": 41.2525527777778,
      "lng": -8.60781666666667
    },
    "locationName": "Vermoim, Porto, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 200,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/60"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/65cd9a25-2046-4f00-b875-c06e8d60e19d.jpg",
    "alt": "20201230_154609618_iOS.heic",
    "date": "2020-12-30T15:46:10.114Z",
    "location": {
      "lat": 40.3473694444444,
      "lng": -7.56123888888889
    },
    "locationName": "Manteigas, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/716"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/7fb3366a-0b79-4a0d-b583-efac5110b8b7.jpg",
    "alt": "20201230_154604279_iOS.heic",
    "date": "2020-12-30T15:46:04.845Z",
    "location": {
      "lat": 40.3473472222222,
      "lng": -7.56124722222222
    },
    "locationName": "Manteigas, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/219"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/6365561a-0c6a-467c-a4cb-2890d93d0e6c.jpg",
    "alt": "20201230_125649904_iOS.heic",
    "date": "2020-12-30T12:56:50.381Z",
    "location": {
      "lat": 40.2737694444444,
      "lng": -7.73814166666667
    },
    "locationName": "Vide, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1199"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/953149b9-13f3-4ec1-9c52-937490db493a.jpg",
    "alt": "20201229_155552694_iOS.heic",
    "date": "2020-12-29T15:55:53.219Z",
    "location": {
      "lat": 40.3814916666667,
      "lng": -7.647175
    },
    "locationName": "São Romão, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/258"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/2f94b9a8-8699-4f36-bd9e-15f887e8dacb.jpg",
    "alt": "20201229_155541752_iOS.heic",
    "date": "2020-12-29T15:55:42.314Z",
    "location": {
      "lat": 40.3815222222222,
      "lng": -7.64711944444444
    },
    "locationName": "São Romão, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 40,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/121"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/22193918-3544-41bc-8492-d0581b3a6bfb.jpg",
    "alt": "20201229_155535523_iOS.heic",
    "date": "2020-12-29T15:55:36.093Z",
    "location": {
      "lat": 40.3817861111111,
      "lng": -7.64768055555556
    },
    "locationName": "São Romão, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 40,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/121"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/f9515746-7545-4fee-af9d-4ad5fb292581.jpg",
    "alt": "20200815_163737138_iOS.heic",
    "date": "2020-08-15T16:37:37.580Z",
    "location": {
      "lat": 37.66935,
      "lng": -7.49460833333333
    },
    "locationName": "Minas de São Domingos, Beja, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/2421"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/a4e5949e-f16f-40eb-8bea-2c00d014d0e0.jpg",
    "alt": "20200813_192324699_iOS.heic",
    "date": "2020-08-13T19:23:25.060Z",
    "location": {
      "lat": 38.3668166666667,
      "lng": -7.35549444444444
    },
    "locationName": "Mourão, Évora, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/320"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/71af7f72-bfe7-4d03-8de8-10d7d2b58746.jpg",
    "alt": "20200813_192231278_iOS.heic",
    "date": "2020-08-13T19:22:31.646Z",
    "location": {
      "lat": 38.3670888888889,
      "lng": -7.35553611111111
    },
    "locationName": "Mourão, Évora, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/375"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/53aba4bd-aadb-484c-aa24-8e5ed078774e.jpg",
    "alt": "20200813_192101428_iOS.heic",
    "date": "2020-08-13T19:21:02.044Z",
    "location": {
      "lat": 38.3678388888889,
      "lng": -7.35526388888889
    },
    "locationName": "Mourão, Évora, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 64,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/122"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/44167f9e-bdca-4ae7-aa4b-8ab93912524d.jpg",
    "alt": "20200813_182203184_iOS.heic",
    "date": "2020-08-13T18:22:03.701Z",
    "location": {
      "lat": 38.6768611111111,
      "lng": -7.40195
    },
    "locationName": "Alandroal, Évora, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/555"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/9907bda2-87d2-4703-9ab5-593f3609e56b.jpg",
    "alt": "20200812_151932424_iOS.heic",
    "date": "2020-08-12T15:19:32.772Z",
    "location": {
      "lat": 39.3708583333333,
      "lng": -7.38810555555556
    },
    "locationName": "Marvão, Portalegre, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/1812"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/93667887-6eee-4e2d-ac37-e3124d901973.jpg",
    "alt": "20200812_135303244_iOS.heic",
    "date": "2020-08-12T13:53:03.740Z",
    "location": {
      "lat": 39.3932416666667,
      "lng": -7.37671111111111
    },
    "locationName": "Marvão, Portalegre, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/1953"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/b48737a7-3a16-400d-b017-e4dcbd394314.jpg",
    "alt": "20200812_134341501_iOS.heic",
    "date": "2020-08-12T13:43:41.912Z",
    "location": {
      "lat": 39.3945277777778,
      "lng": -7.37789444444444
    },
    "locationName": "Marvão, Portalegre, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/3086"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/c272398f-0d20-4363-86e0-e7ca59dfeac9.jpg",
    "alt": "20200812_131046315_iOS.heic",
    "date": "2020-08-12T13:10:46.689Z",
    "location": {
      "lat": 39.3971888888889,
      "lng": -7.38040555555556
    },
    "locationName": "Marvão, Portalegre, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/3937"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/d1d8265a-d891-4ef8-8866-c6597f856e85.jpg",
    "alt": "20200811_150445368_iOS.heic",
    "date": "2020-08-11T15:04:45.796Z",
    "location": {
      "lat": 39.647525,
      "lng": -7.68075
    },
    "locationName": "Vila Velha de Ródão, Castelo Branco, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/4673"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/1a5ebbf5-54d9-4253-9954-a2dac3448afa.jpg",
    "alt": "20200811_130454992_iOS.heic",
    "date": "2020-08-11T13:04:55.343Z",
    "location": {
      "lat": 39.3061833333333,
      "lng": -7.64813055555556
    },
    "locationName": "Alagoa, Portalegre, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/2915"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/c6565dec-4327-490f-a847-35bde6e4b69a.jpg",
    "alt": "20200810_144706570_iOS.heic",
    "date": "2020-08-10T14:47:06.921Z",
    "location": {
      "lat": 40.0378138888889,
      "lng": -7.11486111111111
    },
    "locationName": "Monsanto, Castelo Branco, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/1021"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/58c3fce1-f024-47b7-8c74-566fc5b827d2.jpg",
    "alt": "20200810_123121567_iOS.heic",
    "date": "2020-08-10T12:31:22.054Z",
    "location": {
      "lat": 40.3284638888889,
      "lng": -7.21527777777778
    },
    "locationName": "Sabugal, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/1427"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/05e59df8-72be-4cef-9870-038f5459edac.jpg",
    "alt": "20200809_155314658_iOS.heic",
    "date": "2020-08-09T15:53:15.043Z",
    "location": {
      "lat": 40.2472416666667,
      "lng": -7.81252222222222
    },
    "locationName": "Vide, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/162"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/59ffa7b0-cbb6-47a6-a9b0-486f8b99e617.jpg",
    "alt": "20200809_153148630_iOS.heic",
    "date": "2020-08-09T15:31:49.270Z",
    "location": {
      "lat": 40.2295222222222,
      "lng": -7.825675
    },
    "locationName": "Vide, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/516"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/cd52f1e0-d486-44cc-8563-71fdb0106c77.jpg",
    "alt": "20200809_151349552_iOS.heic",
    "date": "2020-08-09T15:13:49.991Z",
    "location": {
      "lat": 40.2295194444444,
      "lng": -7.82403611111111
    },
    "locationName": "Vide, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/666"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/623231c5-88f4-45bd-9916-d394b3e554b0.jpg",
    "alt": "20200809_151303072_iOS.heic",
    "date": "2020-08-09T15:13:03.446Z",
    "location": {
      "lat": 40.2294083333333,
      "lng": -7.82412222222222
    },
    "locationName": "Vide, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/1610"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/8daf7146-33bb-4e8f-8fd0-6d877c0dc1ec.jpg",
    "alt": "20200809_131853404_iOS.heic",
    "date": "2020-08-09T13:18:53.698Z",
    "location": {
      "lat": 40.2293166666667,
      "lng": -7.82541111111111
    },
    "locationName": "Vide, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/888"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/dc5113fa-0a93-4775-bb36-5acdb3e62123.jpg",
    "alt": "20200809_131229927_iOS.heic",
    "date": "2020-08-09T13:12:30.282Z",
    "location": {
      "lat": 40.2307555555556,
      "lng": -7.82630555555556
    },
    "locationName": "Vide, Guarda, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/440"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/c8185ee7-e346-4a02-9a09-3d9f4cccc82c.jpg",
    "alt": "20200704_202602365_iOS.heic",
    "date": "2020-07-04T20:26:02.753Z",
    "location": {
      "lat": 41.1102527777778,
      "lng": -8.57830833333333
    },
    "locationName": "Vilar de Andorinho, Porto, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 125,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/60"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/6b2c2865-9659-4c3b-9cff-130a4c56de8f.jpg",
    "alt": "20200628_133531517_iOS.heic",
    "date": "2020-06-28T12:35:31.867Z",
    "location": {
      "lat": 41.5414388888889,
      "lng": -6.26680833333333
    },
    "locationName": "Miranda do Douro, Bragança, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/3289"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/26bd165c-39a6-4903-bf16-41a513f34678.jpg",
    "alt": "20200627_182446532_iOS.heic",
    "date": "2020-06-27T18:24:46.917Z",
    "location": {
      "lat": 41.5395166666667,
      "lng": -6.22242222222222
    },
    "locationName": "Villardiegua de la Ribera, Castille and León, Spain",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/1953"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/799ef225-9ddd-421a-973a-aaa08b4c8e3f.jpg",
    "alt": "20200621_161414594_iOS.heic",
    "date": "2020-06-21T16:14:15.155Z",
    "location": {
      "lat": 41.15585,
      "lng": -8.65849444444444
    },
    "locationName": "Pinheiro Manso, Porto, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 40,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/122"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/bbfa4a6a-42d6-4bbc-a409-27f4f25659a2.jpg",
    "alt": "20200621_153758906_iOS.heic",
    "date": "2020-06-21T15:37:59.480Z",
    "location": {
      "lat": 41.1578833333333,
      "lng": -8.65678333333333
    },
    "locationName": "Pinheiro Manso, Porto, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/600"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/3f6b18ec-7916-4d6e-85c9-2704baa4fba8.jpg",
    "alt": "20200317_103203895_iOS.heic",
    "date": "2020-03-17T10:32:04.677Z",
    "location": {
      "lat": 41.2525111111111,
      "lng": -8.60778611111111
    },
    "locationName": "Vermoim, Porto, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 50,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/121"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/d8bf331e-d8ef-479d-ac47-d82833241e7c.jpg",
    "alt": "20200120_175405969_iOS.heic",
    "date": "2020-01-20T17:54:06.293Z",
    "location": {
      "lat": 41.1871,
      "lng": -8.70438055555556
    },
    "locationName": "Leça da Palmeira, Porto, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 100,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/121"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/ec066a30-b10b-47a8-98b0-09a6ea7d8a23.jpg",
    "alt": "20191002_214647450_iOS.heic",
    "date": "2019-10-02T21:46:47.985Z",
    "location": {
      "lat": 41.1471583333333,
      "lng": -8.60521666666667
    },
    "locationName": "Porto, Porto, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 250,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/59"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/a0192612-f1c0-463d-8e87-bfc3e8ec664a.jpg",
    "alt": "20190921_180457326_iOS.heic",
    "date": "2019-09-21T18:04:57.655Z",
    "location": {
      "lat": 38.7282222222222,
      "lng": -9.18455277777778
    },
    "locationName": "Buraca, Lisbon, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/235"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/2cb8c194-ea48-406f-8da8-3b539c7579f0.jpg",
    "alt": "20190921_174301999_iOS.heic",
    "date": "2019-09-21T17:43:02.362Z",
    "location": {
      "lat": 38.7406083333333,
      "lng": -9.15788611111111
    },
    "locationName": "Sete Rios, Lisbon, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 32,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/100"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/d89691f8-8d38-4e91-82e3-e2000d545f28.jpg",
    "alt": "20190810_194706837_iOS.heic",
    "date": "2019-08-10T19:47:07.280Z",
    "location": {
      "lat": 41.2527166666667,
      "lng": -8.60791944444444
    },
    "locationName": "Vermoim, Porto, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 250,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/60"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/b560ab9a-5d8d-4c2f-b763-397cf65b05fc.jpg",
    "alt": "20190622_194820051_iOS.heic",
    "date": "2019-06-22T19:48:20.468Z",
    "location": {
      "lat": 52.9581138888889,
      "lng": -9.44804444444445
    },
    "locationName": "Lehinch, Munster, Ireland",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 32,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/122"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/d844295d-a034-41b1-8124-d7540c3da1ca.jpg",
    "alt": "20190622_192018452_iOS.heic",
    "date": "2019-06-22T19:20:18.819Z",
    "location": {
      "lat": 52.9645944444444,
      "lng": -9.43612222222222
    },
    "locationName": "Lehinch, Munster, Ireland",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/212"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/c833a4a6-f312-4439-a783-cfc6c5347141.jpg",
    "alt": "20190622_144403133_iOS.heic",
    "date": "2019-06-22T14:44:03.585Z",
    "location": {
      "lat": 53.0906361111111,
      "lng": -9.14639444444444
    },
    "locationName": "Lisdoonvarna, Munster, Ireland",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/392"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/e0ec8fef-ce3e-47b9-ad61-1a8dbefec450.jpg",
    "alt": "20190622_105704443_iOS.heic",
    "date": "2019-06-22T10:57:04.864Z",
    "location": {
      "lat": 53.4217833333333,
      "lng": -6.22363611111111
    },
    "locationName": "Kinsealy-Drinan, Leinster, Ireland",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/9524"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/8144f9ff-fa9e-4d2d-95a9-63e96f536352.jpg",
    "alt": "20190620_142854285_iOS.jpg",
    "date": "2019-06-20T14:28:54.285Z",
    "location": {
      "lat": 53.3455055555556,
      "lng": -6.26448888888889
    },
    "locationName": "Dublin, Leinster, Ireland",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1043"
    },
    "dimensions": "4032 × 3021"
  },
  {
    "src": "../public/img/photos/eab0d922-42e0-4af9-90b5-0c2c574754d6.jpg",
    "alt": "20190518_160512558_iOS.jpg",
    "date": "2019-05-18T16:05:12.681Z",
    "location": {
      "lat": 38.7520777777778,
      "lng": -9.1816
    },
    "locationName": "Campo Grande, Lisbon, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1845"
    },
    "dimensions": "3520 × 1980"
  },
  {
    "src": "../public/img/photos/38a24b7d-5c4e-4bc5-b8a1-1c840f98ef36.jpg",
    "alt": "20190518_155028331_iOS.heic",
    "date": "2019-05-18T15:50:28.977Z",
    "location": {
      "lat": 38.7521361111111,
      "lng": -9.1816
    },
    "locationName": "Campo Grande, Lisbon, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1653"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/cff4d79d-3773-4031-8d96-d874faf28416.jpg",
    "alt": "20190425_004209024_iOS.heic",
    "date": "2019-04-25T00:42:09.816Z",
    "location": {
      "lat": 41.1474722222222,
      "lng": -8.61438055555556
    },
    "locationName": "Porto, Porto, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 2000,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/17"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/a420976d-dae1-47d8-a7af-8f45240c30c4.jpg",
    "alt": "20190205_023512336_iOS.heic",
    "date": "2019-02-05T02:35:12.692Z",
    "location": {
      "lat": 10.77565,
      "lng": 106.693008333333
    },
    "locationName": "Quận Ba, Ho Chi Minh, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/450"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/ab8c0b81-0766-4692-8500-539920d869f8.jpg",
    "alt": "20190201_073009630_iOS.heic",
    "date": "2019-02-01T07:30:09.957Z",
    "location": {
      "lat": 15.7630194444444,
      "lng": 108.123908333333
    },
    "locationName": "Đại Cường, Quảng Nam Province, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/500"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/94d0ae2a-f996-4640-b9d4-ab946ccf042f.jpg",
    "alt": "20190131_061114784_iOS.heic",
    "date": "2019-01-31T06:11:15.222Z",
    "location": {
      "lat": 15.8768388888889,
      "lng": 108.328636111111
    },
    "locationName": "Hoi An, Quảng Nam Province, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/1250"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/30775804-af89-4ecc-b7d7-1e65226b29df.jpg",
    "alt": "20190130_142030036_iOS.heic",
    "date": "2019-01-30T14:20:30.541Z",
    "location": {
      "lat": 15.8768027777778,
      "lng": 108.328666666667
    },
    "locationName": "Hoi An, Quảng Nam Province, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 200,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/50"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/ac67cfd4-730a-4e35-96de-461fd282a55b.jpg",
    "alt": "20190130_140929378_iOS.heic",
    "date": "2019-01-30T14:09:29.959Z",
    "location": {
      "lat": 15.8761333333333,
      "lng": 108.3283
    },
    "locationName": "Hoi An, Quảng Nam Province, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 400,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/50"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/27a92d3f-1eb2-439a-a648-7ef2f85c89d3.jpg",
    "alt": "20190127_091532533_iOS.heic",
    "date": "2019-01-27T09:15:32.920Z",
    "location": {
      "lat": 20.2754888888889,
      "lng": 105.863594444444
    },
    "locationName": "Me, Ninh Bình Province, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/705"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/f4f3c056-63b4-4903-9c36-d298d9264ac2.jpg",
    "alt": "20190126_082823084_iOS.heic",
    "date": "2019-01-26T08:28:23.423Z",
    "location": {
      "lat": 20.2300861111111,
      "lng": 105.934288888889
    },
    "locationName": "Ninh Bình, Ninh Bình Province, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/2075"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/aef4bd7a-a714-4ea7-a829-61d3bf380cab.jpg",
    "alt": "20190126_072135172_iOS.heic",
    "date": "2019-01-26T07:21:35.550Z",
    "location": {
      "lat": 20.2299722222222,
      "lng": 105.945733333333
    },
    "locationName": "Ninh Bình, Ninh Bình Province, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/2519"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/494258d9-ed49-42b2-a372-c04bbef6d97d.jpg",
    "alt": "20190125_040512618_iOS.heic",
    "date": "2019-01-25T04:05:13.121Z",
    "location": {
      "lat": 21.0304388888889,
      "lng": 105.844277777778
    },
    "locationName": "Hoàn Kiếm, Hanoi, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 64,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/121"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/20f3cec1-a85d-4329-8ce1-02d5d0a839e7.jpg",
    "alt": "20190124_081623707_iOS.heic",
    "date": "2019-01-24T08:16:24.111Z",
    "location": {
      "lat": 20.9142583333333,
      "lng": 106.999266666667
    },
    "locationName": "Hạ Long, Quảng Ninh, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/727"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/8259e668-9dd6-41af-a2ab-18bf424ac929.jpg",
    "alt": "20190124_061719388_iOS.heic",
    "date": "2019-01-24T06:17:19.759Z",
    "location": {
      "lat": 20.9027972222222,
      "lng": 107.017844444444
    },
    "locationName": "Hạ Long, Quảng Ninh, Vietnam",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/2309"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/f45de8ff-9bdc-4083-9160-7245016ab1dd.jpg",
    "alt": "20190122_034523370_iOS.heic",
    "date": "2019-01-22T03:45:23.873Z",
    "location": {
      "lat": 22.3129972222222,
      "lng": 113.934402777778
    },
    "locationName": "Tung Chung, Islands, Hong Kong",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 64,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/121"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/377dcc79-e8b8-4fdd-8638-029290b53b06.jpg",
    "alt": "20190121_085016334_iOS.jpg",
    "date": "2019-01-21T07:50:16.334Z",
    "location": {
      "lat": 22.1955055555556,
      "lng": 113.546438888889
    },
    "locationName": "Macau, Macao",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/331"
    },
    "dimensions": "2317 × 2317"
  },
  {
    "src": "../public/img/photos/125b8895-4618-44ab-a802-39587535662c.jpg",
    "alt": "20190121_071627958_iOS.jpg",
    "date": "2019-01-21T06:16:27.958Z",
    "location": {
      "lat": 22.187675,
      "lng": 113.547844444444
    },
    "locationName": "Macau, Macao",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1370"
    },
    "dimensions": "2495 × 2495"
  },
  {
    "src": "../public/img/photos/d9fd6fb5-1604-4f7c-b153-d888cac573d1.jpg",
    "alt": "20190121_061511927_iOS.heic",
    "date": "2019-01-21T06:15:12.278Z",
    "location": {
      "lat": 22.1863583333333,
      "lng": 113.546316666667
    },
    "locationName": "Macau, Macao",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/1653"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/01521536-e231-4a30-a634-30093f2a517f.jpg",
    "alt": "20190120_093615545_iOS.heic",
    "date": "2019-01-20T09:36:15.891Z",
    "location": {
      "lat": 22.2839611111111,
      "lng": 114.212494444444
    },
    "locationName": "Nam Fung Sun Chuen, Eastern, Hong Kong",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/139"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/0666014c-481e-4b9b-ae9d-e46d771bb92f.jpg",
    "alt": "20190120_090304677_iOS.heic",
    "date": "2019-01-20T09:03:05.169Z",
    "location": {
      "lat": 22.2845888888889,
      "lng": 114.213294444444
    },
    "locationName": "Nam Fung Sun Chuen, Eastern, Hong Kong",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/263"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/42479e97-88e9-4cde-8608-c2e1048c300a.jpg",
    "alt": "20190120_085852191_iOS.heic",
    "date": "2019-01-20T08:58:52.590Z",
    "location": {
      "lat": 22.2844861111111,
      "lng": 114.215522222222
    },
    "locationName": "Tai Koo, Eastern, Hong Kong",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/424"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/d78ec926-9ea8-44aa-a567-01f6aee77b0a.jpg",
    "alt": "20190120_081450489_iOS.heic",
    "date": "2019-01-20T08:14:50.873Z",
    "location": {
      "lat": 22.2790305555556,
      "lng": 114.164122222222
    },
    "locationName": "Admiralty, Central and Western, Hong Kong",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/623"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/f032e54b-dd2d-4bef-9917-ad22be506b56.jpg",
    "alt": "20190120_045906181_iOS.heic",
    "date": "2019-01-20T04:59:06.506Z",
    "location": {
      "lat": 22.2930166666667,
      "lng": 114.170722222222
    },
    "locationName": "Tsim Sha Tsui, Kowloon City, Hong Kong",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 16,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/2994"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/38d04b56-3374-41b5-96a2-ceda218387e6.jpg",
    "alt": "20190120_025822065_iOS.jpg",
    "date": "2019-01-20T02:58:22.065Z",
    "location": {
      "lat": 22.3346694444444,
      "lng": 114.207183333333
    },
    "locationName": "Choi Hung, Wong Tai Sin, Hong Kong",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 25,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/1447"
    },
    "dimensions": "4032 × 3021"
  },
  {
    "src": "../public/img/photos/a53f6fca-9a0a-4a6e-aae8-7f81cfc230e8.jpg",
    "alt": "20190119_102250498_iOS.heic",
    "date": "2019-01-19T10:22:51.171Z",
    "location": {
      "lat": 22.3231388888889,
      "lng": 114.166305555556
    },
    "locationName": "Tai Kok Tsui, Yau Tsim Mong, Hong Kong",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 800,
      "aperture": "f/2.4",
      "focalLength": "6mm",
      "exposureTime": "1/33"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/bad30b7d-f86d-465c-ae19-fc17e418a8a1.jpg",
    "alt": "20190116_160457576_iOS.heic",
    "date": "2019-01-16T16:04:58.358Z",
    "location": {
      "lat": 41.1372388888889,
      "lng": -8.61199166666667
    },
    "locationName": "Porto, Porto, Portugal",
    "camera": "Apple iPhone XS",
    "techDetails": {
      "iso": 1000,
      "aperture": "f/1.8",
      "focalLength": "4.25mm",
      "exposureTime": "1/17"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/92320e15-cb8f-499c-aa34-aa6daf2876f3.jpg",
    "alt": "IMG_0837.JPG",
    "date": "2018-09-11T18:39:55.899Z",
    "location": {
      "lat": 37.1570055555556,
      "lng": -7.54573055555556
    },
    "locationName": "Vila Nova De Cacela, Faro, Portugal",
    "camera": "Apple iPhone 6s",
    "techDetails": {
      "iso": 32,
      "aperture": "f/2.2",
      "focalLength": "4.15mm",
      "exposureTime": "1/100"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/6f9f067c-d072-49ce-aa0a-5d323b0e2fb7.jpg",
    "alt": "IMG_0810.JPG",
    "date": "2018-09-11T17:04:57.079Z",
    "location": {
      "lat": 37.1538888888889,
      "lng": -7.55352777777778
    },
    "locationName": "Vila Nova De Cacela, Faro, Portugal",
    "camera": "Apple iPhone 6s",
    "techDetails": {
      "iso": 25,
      "aperture": "f/2.2",
      "focalLength": "4.15mm",
      "exposureTime": "1/1374"
    },
    "dimensions": "4032 × 3024"
  },
  {
    "src": "../public/img/photos/27200adc-efa0-4e94-9b61-1959779cf711.jpg",
    "alt": "IMG_0269-PANO.jpg",
    "date": "2018-06-24T14:23:00.000Z",
    "location": {
      "lat": 52.2471555555556,
      "lng": 21.0134444444444
    },
    "locationName": "Praga Północ, Mazovia, Poland",
    "camera": "Apple iPhone 6s",
    "techDetails": {
      "focalLength": "4.150000095mm"
    },
    "dimensions": "5144 × 2582"
  },
  {
    "src": "../public/img/photos/0957c196-2ae4-43c4-9ec4-b956aa7d1184.jpg",
    "alt": "IMG_20171118_143124.jpg",
    "date": "2017-11-18T14:31:25.155Z",
    "location": {
      "lat": 41.1693638888889,
      "lng": -8.688275
    },
    "locationName": "Nevogilde, Porto, Portugal",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/1116"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/ebc6b0ea-cad7-4933-9999-d26061c5996c.jpg",
    "alt": "IMG_20171008_193421.jpg",
    "date": "2017-10-08T18:34:21.290Z",
    "location": {
      "lat": 41.7016151666667,
      "lng": -8.83549463888889
    },
    "locationName": "Viana do Castelo, Viana do Castelo, Portugal",
    "camera": "QCOM-AA QCAM-AA",
    "techDetails": {
      "iso": 506,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/33"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/b32b38ba-008d-4a14-a52d-ffebbd02f931.jpg",
    "alt": "IMG_20170724_182450.jpg",
    "date": "2017-07-24T17:24:52.907Z",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/101"
    },
    "dimensions": "3120 × 4160"
  },
  {
    "src": "../public/img/photos/195c5704-424b-4315-8a3c-ce5b284a46af.jpg",
    "alt": "IMG_20170605_164501.jpg",
    "date": "2017-06-05T14:45:02.567Z",
    "location": {
      "lat": 41.4146722222222,
      "lng": 2.15446666666667
    },
    "locationName": "Barcelona, Catalonia, Spain",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/488"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/5086ecc4-5af4-4752-8865-f5e895112b8d.jpg",
    "alt": "IMG_20170531_192922.jpg",
    "date": "2017-05-31T17:29:23.312Z",
    "location": {
      "lat": 41.4111333333333,
      "lng": 2.218925
    },
    "locationName": "Sant Martí, Catalonia, Spain",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 101,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/1345"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/4c2cbe13-4e69-4fc8-ac84-7d0ba70ea756.jpg",
    "alt": "IMG_20170519_135336.jpg",
    "date": "2017-05-19T12:53:37.167Z",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/280"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/8aa093b1-ed8f-4bf4-b84f-0a6fbba2a3f4.jpg",
    "alt": "IMG_20170519_153454.jpg",
    "date": "2017-05-19T12:34:55.242Z",
    "location": {
      "lat": 44.4203388888889,
      "lng": 26.1504277777778
    },
    "locationName": "Bucharest, București, Romania",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/677"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/79049a14-a3e8-4b60-8881-dcf6e9bb1fd2.jpg",
    "alt": "IMG_20170426_182242.jpg",
    "date": "2017-04-26T17:22:42.645Z",
    "location": {
      "lat": 37.0724416666667,
      "lng": -8.77073055555556
    },
    "locationName": "Senhora da Luz, Faro, Portugal",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/386"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/164869b8-b520-4db6-9748-7ec8c13933d2.jpg",
    "alt": "IMG_20170425_200842.jpg",
    "date": "2017-04-25T19:08:42.664Z",
    "location": {
      "lat": 37.1854527777778,
      "lng": -8.89494722222222
    },
    "locationName": "Vila do Bispo, Faro, Portugal",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/433"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/84fcfe8b-150c-4208-8a95-3f115c8d431d.jpg",
    "alt": "IMG_20170326_220409.jpg",
    "date": "2017-03-27T02:04:09.964Z",
    "location": {
      "lat": 25.7759935277778,
      "lng": -80.1870973611111
    },
    "locationName": "Miami, Florida, United States of America",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 257,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/33"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/6bb536a8-aebf-47c0-84e4-21540970e3b6.jpg",
    "alt": "DCIM\\100GOPRO\\GOPR3379.",
    "date": "2017-03-25T18:20:35.000Z",
    "description": "DCIM\\100GOPRO\\GOPR3379.",
    "camera": "GoPro HERO4 Black",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.8",
      "focalLength": "3mm",
      "exposureTime": "1/352"
    },
    "dimensions": "4000 × 3000"
  },
  {
    "src": "../public/img/photos/18dd6ce2-4993-4fe4-a435-546cfef47bd0.jpg",
    "alt": "IMG_20170122_165833.jpg",
    "date": "2017-01-22T16:58:35.656Z",
    "camera": "OnePlus QCAM-AA",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/1295"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/2b9fbc1b-f5cc-4535-9739-fafcac58ef2e.jpg",
    "alt": "IMG_20160820_154040.jpg",
    "date": "2016-08-20T14:40:40.081Z",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 120,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/100"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/2458652c-1081-449a-acb9-dcd05ae9619b.jpg",
    "alt": "IMG_20160818_214547.jpg",
    "date": "2016-08-18T20:45:47.910Z",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 2284,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/17"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/57ded79a-d1e9-431b-afd6-03d41f3ec9c8.jpg",
    "alt": "IMG_20160709_220628.jpg",
    "date": "2016-07-09T21:06:28.015Z",
    "location": {
      "lat": 40.1492356944444,
      "lng": -8.87265444444444
    },
    "locationName": "Figueira da Foz, Coimbra, Portugal",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 256,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/50"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/a1ac8f64-551b-41f5-a487-06350606f4d7.jpg",
    "alt": "IMG_20160709_014107.jpg",
    "date": "2016-07-09T00:41:07.452Z",
    "location": {
      "lat": 40.1491370555556,
      "lng": -8.87250713888889
    },
    "locationName": "Figueira da Foz, Coimbra, Portugal",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 280,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/33"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/eac39ddd-89d8-4f32-bf84-0d15fde77ac4.jpg",
    "alt": "IMG_20160703_194808.jpg",
    "date": "2016-07-03T18:48:08.110Z",
    "location": {
      "lat": 41.3797882222222,
      "lng": -7.86293655555556
    },
    "locationName": "Mondim de Basto, Vila Real, Portugal",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/386"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/fd0b124b-b89d-43e4-a9b8-4370dd4900f3.jpg",
    "alt": "DCIM\\100GOPRO\\GOPR1836.",
    "date": "2016-07-03T16:06:05.000Z",
    "description": "DCIM\\100GOPRO\\GOPR1836.",
    "camera": "GoPro HERO4 Black",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.8",
      "focalLength": "3mm",
      "exposureTime": "1/1799"
    },
    "dimensions": "4000 × 3000"
  },
  {
    "src": "../public/img/photos/450b6c30-a193-4c1f-81cc-7a9254502667.jpg",
    "alt": "IMG_20160628_103943.jpg",
    "date": "2016-06-28T09:39:43.185Z",
    "location": {
      "lat": 38.743776,
      "lng": -9.151843
    },
    "locationName": "Campo Pequeno, Lisbon, Portugal",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/166"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/3d9a5d41-a7d8-46ab-abbe-67fa2b39a72b.jpg",
    "alt": "IMG_20160620_135421.jpg",
    "date": "2016-06-20T12:54:21.228Z",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/718"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/dd198fb7-70b0-4ad7-9a76-eeeafd5c0467.jpg",
    "alt": "IMG_20160617_212708.jpg",
    "date": "2016-06-17T19:27:07.896Z",
    "location": {
      "lat": 55.6657015555556,
      "lng": 12.5798776944444
    },
    "locationName": "Christianshavn, Capital Region, Denmark",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 355,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/33"
    },
    "dimensions": "3120 × 4160"
  },
  {
    "src": "../public/img/photos/1f5920f8-1698-4912-a25a-6a9c43ccd49b.jpg",
    "alt": "IMG_20160617_212503_004.jpg",
    "date": "2016-06-17T19:25:03.341Z",
    "location": {
      "lat": 55.6656333888889,
      "lng": 12.5826243611111
    },
    "locationName": "Christianshavn, Capital Region, Denmark",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 265,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/33"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/430a0d8c-70ca-40a7-9dde-db0e68f1c37c.jpg",
    "alt": "IMG_20160604_185342.jpg",
    "date": "2016-06-04T17:53:42.322Z",
    "location": {
      "lat": 41.15636425,
      "lng": -8.65666463888889
    },
    "locationName": "Pinheiro Manso, Porto, Portugal",
    "camera": "OnePlus2 ONE A2003",
    "techDetails": {
      "iso": 101,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/1873"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/3b1ae2d7-345f-4241-a77e-3373b94062fe.jpg",
    "alt": "IMG_20160522_092439.jpg",
    "date": "2016-05-22T08:24:39.256Z",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/718"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/b0c63976-e230-484d-93e1-c9c78a4ee340.jpg",
    "alt": "IMG_20160520_133534.jpg",
    "date": "2016-05-20T12:35:34.541Z",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 223,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/40"
    },
    "dimensions": "3120 × 4160"
  },
  {
    "src": "../public/img/photos/8449b40f-ce21-4866-9960-9de5820b6935.jpg",
    "alt": "IMG_20160519_153132.jpg",
    "date": "2016-05-19T14:31:32.808Z",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 897,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/25"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/45c841d4-f2a5-49ab-b6e9-e97638c84884.jpg",
    "alt": "IMG_20160519_181743.jpg",
    "date": "2016-05-19T10:17:43.553Z",
    "location": {
      "lat": 31.2215156944444,
      "lng": 121.469826333333
    },
    "locationName": "Shanghai, Shanghai, People's Republic of China",
    "camera": "OnePlus QCAM-AA",
    "techDetails": {
      "iso": 306,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/33"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/c3e98e0b-6676-4f52-b029-91412731a1ad.jpg",
    "alt": "IMG_20160513_135733.jpg",
    "date": "2016-05-13T05:57:33.444Z",
    "location": {
      "lat": 31.2241810277778,
      "lng": 121.471300861111
    },
    "locationName": "Shanghai, Shanghai, People's Republic of China",
    "camera": "OnePlus QCAM-AA",
    "techDetails": {
      "iso": 359,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/30"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/d8fdf3b9-b2ef-4900-99f6-474459ba2e07.jpg",
    "alt": "IMG_20160513_101112.jpg",
    "date": "2016-05-13T02:11:12.272Z",
    "location": {
      "lat": 31.2201791944444,
      "lng": 121.470313027778
    },
    "locationName": "Shanghai, Shanghai, People's Republic of China",
    "camera": "OnePlus QCAM-AA",
    "techDetails": {
      "iso": 210,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/100"
    },
    "dimensions": "3120 × 4160"
  },
  {
    "src": "../public/img/photos/c58f825b-6df2-45f5-92c1-ad6e9ed9fa62.jpg",
    "alt": "IMG_20160511_084533.jpg",
    "date": "2016-05-11T07:45:33.175Z",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 199,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/100"
    },
    "dimensions": "3120 × 4160"
  },
  {
    "src": "../public/img/photos/7f9d6fae-3509-40a0-8432-92e76ebd694c.jpg",
    "alt": "IMG_20160419_201652.jpg",
    "date": "2016-04-19T19:16:52.372Z",
    "location": {
      "lat": 41.1792486388889,
      "lng": -8.622268
    },
    "locationName": "Bairro Silva Braga, Porto, Portugal",
    "camera": "OnePlus QCAM-AA",
    "techDetails": {
      "iso": 215,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/50"
    },
    "dimensions": "3120 × 4160"
  },
  {
    "src": "../public/img/photos/4288b94a-0468-4695-9907-d9d520b6aaeb.jpg",
    "alt": "IMG_20160416_114530.jpg",
    "date": "2016-04-16T10:45:30.028Z",
    "location": {
      "lat": 40.1528935555556,
      "lng": -8.85030466666667
    },
    "locationName": "Figueira da Foz, Coimbra, Portugal",
    "camera": "OnePlus QCAM-AA",
    "techDetails": {
      "iso": 256,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/50"
    },
    "dimensions": "3120 × 4160"
  },
  {
    "src": "../public/img/photos/73bcc44a-709b-4e4f-af27-1d7e706e3b57.jpg",
    "alt": "IMG_20160410_064400.jpg",
    "date": "2016-04-10T05:44:00.190Z",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 3775,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/17"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/1b1baf3a-e843-49ba-86e2-ea4eab53c797.jpg",
    "alt": "IMG_20160408_213906.jpg",
    "date": "2016-04-08T20:39:06.133Z",
    "location": {
      "lat": 41.4968626944444,
      "lng": -8.36401211111111
    },
    "locationName": "Taipas, Braga, Portugal",
    "camera": "OnePlus QCAM-AA",
    "techDetails": {
      "iso": 3775,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/17"
    },
    "dimensions": "3120 × 4160"
  },
  {
    "src": "../public/img/photos/053aacc1-1f2f-40c3-b7f6-c2e2dc7ca189.jpg",
    "alt": "IMG_20160306_082038.jpg",
    "date": "2016-03-06T08:20:38.845Z",
    "location": {
      "lat": 41.261237,
      "lng": -8.616659
    },
    "locationName": "Anta, Porto, Portugal",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 399,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/33"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/65578ebb-bf5b-4b8e-86ca-c168a2b11d46.jpg",
    "alt": "IMG_20160303_202024.jpg",
    "date": "2016-03-03T20:20:24.614Z",
    "location": {
      "lat": 41.2526739722222,
      "lng": -8.60785897222222
    },
    "locationName": "Vermoim, Porto, Portugal",
    "camera": "OnePlus ONE A2003",
    "techDetails": {
      "iso": 788,
      "aperture": "f/2",
      "focalLength": "4.48mm",
      "exposureTime": "1/33"
    },
    "dimensions": "4160 × 3120"
  },
  {
    "src": "../public/img/photos/984a11dc-2a82-4cb2-b3a3-b3fd5dab67f3.jpg",
    "alt": "IMG_20160206_151355.jpg",
    "date": "2016-02-06T11:13:57.000Z",
    "location": {
      "lat": 25.2446555555556,
      "lng": 55.3698055555556
    },
    "locationName": "Bur Dubai, Dubai, United Arab Emirates",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1401"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/02c09f22-2ff9-4612-a7c9-ee682ba85366.jpg",
    "alt": "DSC01853.ARW",
    "date": "2016-02-05T01:08:46.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 100,
      "aperture": "f/9",
      "focalLength": "50mm",
      "exposureTime": "1/125"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/028946e9-3467-4380-8405-9c0620df2b29.jpg",
    "alt": "DSC01846.ARW",
    "date": "2016-02-03T05:21:42.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 100,
      "aperture": "f/11",
      "focalLength": "50mm",
      "exposureTime": "1/250"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/52883a03-3904-4cee-afc5-1d52a66bf898.jpg",
    "alt": "DSC01840.ARW",
    "date": "2016-02-01T08:39:52.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 800,
      "aperture": "f/5.6",
      "focalLength": "50mm",
      "exposureTime": "1/80"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/8a445146-40b6-4880-af0c-687b1c46d915.jpg",
    "alt": "IMG_20160201_134724.jpg",
    "date": "2016-02-01T03:47:25.000Z",
    "location": {
      "lat": -28.0026222222222,
      "lng": 153.431466666667
    },
    "locationName": "Surfers Paradise, Queensland, Australia",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1543"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/745a51b8-e0e0-4d9b-86a8-4da86525daa9.jpg",
    "alt": "DSC01835.ARW",
    "date": "2016-01-30T11:47:15.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 3200,
      "aperture": "f/5.6",
      "focalLength": "50mm",
      "exposureTime": "1/60"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/c193b566-5944-4acf-ac51-7063caca41b9.jpg",
    "alt": "DSC01818.ARW",
    "date": "2016-01-29T19:39:26.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 3200,
      "aperture": "f/5.6",
      "focalLength": "50mm",
      "exposureTime": "1/30"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/d6d062a2-dae3-466f-a34f-a02aa3fa6a5f.jpg",
    "alt": "DSC01812.ARW",
    "date": "2016-01-29T19:39:05.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 3200,
      "aperture": "f/5.6",
      "focalLength": "50mm",
      "exposureTime": "1/60"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/78d29e14-05be-4585-809d-05ea20817fe1.jpg",
    "alt": "DSC01772.ARW",
    "date": "2016-01-29T15:28:04.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 6400,
      "aperture": "f/5.6",
      "focalLength": "50mm",
      "exposureTime": "1/50"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/eff949f2-c1af-4d71-b5a7-9c8245798acc.jpg",
    "alt": "IMG_20160129_131645.jpg",
    "date": "2016-01-29T05:16:47.000Z",
    "location": {
      "lat": -31.7106777777778,
      "lng": 115.788766666667
    },
    "locationName": "Tapping, Western Australia, Australia",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/3145"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/4a998eca-ebc5-4c9f-9fc8-f962f3fcf307.jpg",
    "alt": "DSC01686.ARW",
    "date": "2016-01-29T05:16:25.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 100,
      "aperture": "f/11",
      "focalLength": "45mm",
      "exposureTime": "1/400"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/9ba931bb-0e6d-49ce-95cd-ddbb55462a31.jpg",
    "alt": "DSC01670.ARW",
    "date": "2016-01-29T02:54:03.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 100,
      "aperture": "f/8",
      "focalLength": "50mm",
      "exposureTime": "1/100"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/051eab5b-e2f8-4650-8586-1d9f0509703c.jpg",
    "alt": "IMG_20160126_100524.jpg",
    "date": "2016-01-26T02:05:26.239Z",
    "location": {
      "lat": -31.9397527777778,
      "lng": 115.846966666667
    },
    "locationName": "Leederville, Western Australia, Australia",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/2699"
    },
    "dimensions": "3264 × 2448"
  },
  {
    "src": "../public/img/photos/0475bfe2-4c9d-4499-b28d-6fef4b66e2bd.jpg",
    "alt": "IMG_20160125_183538.jpg",
    "date": "2016-01-25T10:35:40.000Z",
    "location": {
      "lat": -31.7296194444444,
      "lng": 115.790244444444
    },
    "locationName": "Ashby, Western Australia, Australia",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/727"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/4d329081-413f-4f68-b597-86a2979440f2.jpg",
    "alt": "IMG_20160123_141439.jpg",
    "date": "2016-01-23T14:14:40.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1845"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/46745328-de83-4640-a2f3-0d03589ec8ad.jpg",
    "alt": "IMG_20160123_133942.jpg",
    "date": "2016-01-23T13:39:43.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1199"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/f51cb2ec-6de1-45f7-a59c-070c8bc006b7.jpg",
    "alt": "DSC01644.ARW",
    "date": "2016-01-23T05:32:50.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 100,
      "aperture": "f/11",
      "focalLength": "16mm",
      "exposureTime": "1/125"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/b5f9ed65-420c-4d67-9e25-13ce5baf2a4b.jpg",
    "alt": "IMG_20160123_133053.jpg",
    "date": "2016-01-23T05:30:55.000Z",
    "location": {
      "lat": 31.2409,
      "lng": 121.495625
    },
    "locationName": "Pudong, Shanghai, People's Republic of China",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/2160"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/27d7f955-9c86-4577-b1aa-2e8ee11d0692.jpg",
    "alt": "IMG_20160122_165906.jpg",
    "date": "2016-01-22T08:59:08.000Z",
    "location": {
      "lat": 30.6676972222222,
      "lng": 114.294388888889
    },
    "locationName": "Houhu, Hubei, People's Republic of China",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 129,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/80"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/b36dc498-fa21-4524-9d9a-87fc619d2f1a.jpg",
    "alt": "IMG_20160122_160630.jpg",
    "date": "2016-01-22T08:06:32.000Z",
    "location": {
      "lat": 30.6117277777778,
      "lng": 114.305541666667
    },
    "locationName": "Jiang’an Qu, Hubei, People's Republic of China",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 198,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/55"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/62e21a3a-eb25-4ef5-8699-9aedcdd379b2.jpg",
    "alt": "IMG_20160120_104253.jpg",
    "date": "2016-01-20T10:42:54.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/109"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/46be6844-10bd-4d62-91f9-e08787cd8ac8.jpg",
    "alt": "IMG_20160119_193533.jpg",
    "date": "2016-01-19T11:35:35.000Z",
    "location": {
      "lat": 31.2254972222222,
      "lng": 121.475536111111
    },
    "locationName": "Shanghai, Shanghai, People's Republic of China",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 382,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/31"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/a65a66c2-179b-44e2-8551-c1f71499e752.jpg",
    "alt": "IMG_20160119_193155.jpg",
    "date": "2016-01-19T11:31:56.000Z",
    "location": {
      "lat": 31.2254972222222,
      "lng": 121.475536111111
    },
    "locationName": "Shanghai, Shanghai, People's Republic of China",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 263,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/43"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/f1a2c6f7-5fc1-4401-9720-e2f586b79bea.jpg",
    "alt": "DSC01601.ARW",
    "date": "2016-01-19T08:47:17.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 100,
      "aperture": "f/11",
      "focalLength": "28mm",
      "exposureTime": "1/100"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/53abb86d-4753-4e09-8750-fbf2de834f1f.jpg",
    "alt": "DSC01552.ARW",
    "date": "2016-01-15T13:03:04.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 100,
      "aperture": "f/11",
      "focalLength": "37mm",
      "exposureTime": "1/125"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/fbae4cdb-bfff-4c6c-b89c-2b38822bd5f7.jpg",
    "alt": "DSC01536.ARW",
    "date": "2016-01-15T12:40:08.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 100,
      "aperture": "f/8",
      "focalLength": "16mm",
      "exposureTime": "1/100"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/e1f8b4ff-cbd6-43c2-968f-4d771520c878.jpg",
    "alt": "DSC01531.ARW",
    "date": "2016-01-15T12:35:52.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 100,
      "aperture": "f/9",
      "focalLength": "50mm",
      "exposureTime": "1/125"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/42ed181f-0fb8-41ea-bcf1-e531cfbcdd0a.jpg",
    "alt": "DSC01517.ARW",
    "date": "2016-01-15T11:56:28.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 100,
      "aperture": "f/11",
      "focalLength": "16mm",
      "exposureTime": "1/200"
    },
    "dimensions": "6048 × 4024"
  },
  {
    "src": "../public/img/photos/eccd4405-0b84-4d01-bd33-8b2721918f6e.jpg",
    "alt": "DSC01505.JPG",
    "date": "2016-01-14T20:07:49.000Z",
    "camera": "SONY ILCE-6000",
    "techDetails": {
      "iso": 6400,
      "aperture": "f/3.5",
      "focalLength": "16mm",
      "exposureTime": "1/20"
    },
    "dimensions": "6000 × 4000"
  },
  {
    "src": "../public/img/photos/14766da4-d004-49ea-a60f-ca421bc02eef.jpg",
    "alt": "DCIM\\101GOPRO\\GOPR1478.",
    "date": "2016-01-02T14:33:08.000Z",
    "description": "DCIM\\101GOPRO\\GOPR1478.",
    "camera": "GoPro HERO4 Black",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.8",
      "focalLength": "3mm",
      "exposureTime": "1/1590"
    },
    "dimensions": "4000 × 3000"
  },
  {
    "src": "../public/img/photos/2c564501-ffe4-4e58-bb9a-882bc14e7e01.jpg",
    "alt": "DCIM\\100GOPRO\\GOPR0075.",
    "date": "2015-12-29T18:21:01.000Z",
    "description": "DCIM\\100GOPRO\\GOPR0075.",
    "camera": "GoPro HERO4 Black",
    "techDetails": {
      "iso": 400,
      "aperture": "f/2.8",
      "focalLength": "3mm",
      "exposureTime": "1/6"
    },
    "dimensions": "4000 × 3000"
  },
  {
    "src": "../public/img/photos/7aee3052-3917-49a5-8dd1-1de0b9b7bbe4.jpg",
    "alt": "IMG_20151030_152348.jpg",
    "date": "2015-10-30T14:23:51.000Z",
    "location": {
      "lat": 55.6929877777778,
      "lng": 12.5991858333333
    },
    "locationName": "Christianshavn, Capital Region, Denmark",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/112"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/7ba17c6d-dac5-426c-968b-e9fc1b83695b.jpg",
    "alt": "IMG_20151030_144948.jpg",
    "date": "2015-10-30T13:49:50.000Z",
    "location": {
      "lat": 55.6800155555556,
      "lng": 12.5893177777778
    },
    "locationName": "Christianshavn, Capital Region, Denmark",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/298"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/330073c2-9be4-4ec8-8cc8-1f0d4093bee7.jpg",
    "alt": "IMG_20151007_141020.jpg",
    "date": "2015-10-07T12:10:23.000Z",
    "location": {
      "lat": 51.3543388888889,
      "lng": 3.29748305555556
    },
    "locationName": "Knokke, Flanders, Belgium",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/279"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/b3d1d635-8484-4a36-a65f-5098f2766394.jpg",
    "alt": "IMG_20151007_121818.jpg",
    "date": "2015-10-07T10:18:23.000Z",
    "location": {
      "lat": 51.3547741666667,
      "lng": 3.29944472222222
    },
    "locationName": "Knokke, Flanders, Belgium",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/110"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/2c6fa153-1174-499a-ad24-af2884138b54.jpg",
    "alt": "IMG_20151006_171111.jpg",
    "date": "2015-10-06T15:11:14.000Z",
    "location": {
      "lat": 51.3555536111111,
      "lng": 3.29931555555556
    },
    "locationName": "Knokke, Flanders, Belgium",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 121,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/84"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/88da9ba8-2510-4243-81d0-6049032d6b70.jpg",
    "alt": "IMG_20150920_072413.jpg",
    "date": "2015-09-20T06:24:33.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/3610"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/f5291be5-f61b-44f9-aca9-2754330d4625.jpg",
    "alt": "IMG_20150820_195221.jpg",
    "date": "2015-08-20T18:52:25.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/114"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/4b93a218-5940-4490-82bf-f261b854341b.jpg",
    "alt": "IMG_20150820_002727.jpg",
    "date": "2015-08-19T23:27:31.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 774,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/16"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/80165afb-62ea-465a-b524-8078699635a4.jpg",
    "alt": "IMG_20150819_175102.jpg",
    "date": "2015-08-19T16:51:12.000Z",
    "location": {
      "lat": 41.9194952777778,
      "lng": -8.56915861111111
    },
    "locationName": "Paredes de Coura, Viana do Castelo, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/450"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/9ed5334b-9347-4b81-ae7c-6a32c84015c5.jpg",
    "alt": "IMG_20150819_162244.jpg",
    "date": "2015-08-19T15:22:50.000Z",
    "location": {
      "lat": 41.9200427777778,
      "lng": -8.56737611111111
    },
    "locationName": "Paredes de Coura, Viana do Castelo, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/171"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/915505ea-e79d-4ca2-8c75-e0bcac6e5a68.jpg",
    "alt": "PANO_20150802_193940.jpg",
    "date": "2015-08-02T18:41:13.000Z",
    "location": {
      "lat": 41.3729769444444,
      "lng": -7.87876277777778
    },
    "locationName": "Mondim de Basto, Vila Real, Portugal",
    "camera": "LGE Nexus 5",
    "dimensions": "7936 × 1962"
  },
  {
    "src": "../public/img/photos/9b491e8b-223c-4b0a-9cf1-760865171f8a.jpg",
    "alt": "IMG_20150730_195214.jpg",
    "date": "2015-07-30T17:52:17.000Z",
    "location": {
      "lat": 40.5229591666667,
      "lng": -4.71606527777778
    },
    "locationName": "San Juan de la Nava, Castille and León, Spain",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/4464"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/5bded13e-2114-4199-9ac0-4113c4a10b0e.jpg",
    "alt": "IMG_20150730_132724-PANO.jpg",
    "date": "2015-07-30T11:27:27.000Z",
    "location": {
      "lat": 40.4523308333333,
      "lng": -3.68967
    },
    "locationName": "Chamartín, Madrid, Spain",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "focalLength": "3.970000029mm"
    },
    "dimensions": "4119 × 1186"
  },
  {
    "src": "../public/img/photos/5dee2542-a4f7-4e32-8747-c93d7285122a.jpg",
    "alt": "PANO_20150730_132324.jpg",
    "date": "2015-07-30T11:24:22.000Z",
    "location": {
      "lat": 40.4531477777778,
      "lng": -3.68985
    },
    "locationName": "Chamartín, Madrid, Spain",
    "camera": "LGE Nexus 5",
    "dimensions": "6480 × 1870"
  },
  {
    "src": "../public/img/photos/b9ba80d1-3e58-4752-994a-925295ab6603.jpg",
    "alt": "IMG_20150723_115624.jpg",
    "date": "2015-07-23T09:56:27.000Z",
    "location": {
      "lat": 52.5141166666667,
      "lng": 13.3793944444444
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/2101"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/c6bece2c-c1a7-4704-a929-22c35fd34be1.jpg",
    "alt": "IMG_20150722_205204.jpg",
    "date": "2015-07-22T18:52:07.000Z",
    "location": {
      "lat": 52.5153458333333,
      "lng": 13.4068066666667
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/413"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/e7a85a31-b9b4-47e6-9f5e-44b1007fd494.jpg",
    "alt": "IMG_20150722_183101.jpg",
    "date": "2015-07-22T16:31:04.000Z",
    "location": {
      "lat": 52.5194294444444,
      "lng": 13.4067111111111
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1761"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/5716397d-6a3a-4cc0-b1f0-4cb968a87498.jpg",
    "alt": "IMG_20150722_175617.jpg",
    "date": "2015-07-22T15:56:20.000Z",
    "location": {
      "lat": 52.51918,
      "lng": 13.3948527777778
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1610"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/bd8feb86-2870-45da-8f19-8da64a3c019d.jpg",
    "alt": "IMG_20150722_171021.jpg",
    "date": "2015-07-22T15:10:23.000Z",
    "location": {
      "lat": 52.5194772222222,
      "lng": 13.3768466666667
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1351"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/8077e33b-5fcf-4ddc-baf5-afb0b8c04f59.jpg",
    "alt": "IMG_20150722_165728.jpg",
    "date": "2015-07-22T14:57:36.000Z",
    "location": {
      "lat": 52.5163516666667,
      "lng": 13.3786077777778
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/3436"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/3c77c6b2-fcc8-432f-977a-3dcd54fb9f2d.jpg",
    "alt": "IMG_20150722_150349.jpg",
    "date": "2015-07-22T13:03:53.000Z",
    "location": {
      "lat": 52.5102408333333,
      "lng": 13.4039888888889
    },
    "locationName": "Berlin, Berlin, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 160,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/66"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/6e522ad4-8c4d-418a-bd58-01d5549da87b.jpg",
    "alt": "IMG_20150721_114258.jpg",
    "date": "2015-07-21T09:43:01.000Z",
    "location": {
      "lat": 51.0535172222222,
      "lng": 13.7350291666667
    },
    "locationName": "Dresden, Saxony, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1376"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/62c9dcb9-3563-4cdb-9501-82ef420a3ca5.jpg",
    "alt": "IMG_20150720_135010.jpg",
    "date": "2015-07-20T11:50:14.000Z",
    "location": {
      "lat": 50.940175,
      "lng": 6.95627527777778
    },
    "locationName": "Köln, North Rhine-Westphalia, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1163"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/1dde03c7-c375-48bf-8253-695310b32a3d.jpg",
    "alt": "IMG_20150714_141333.jpg",
    "date": "2015-07-14T12:13:35.000Z",
    "location": {
      "lat": 48.1413644444444,
      "lng": 11.5649769444444
    },
    "locationName": "Munich, Bavaria, Germany",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/494"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/5731e077-92b2-43c7-8d19-d0eb8b29c405.jpg",
    "alt": "IMG_20150705_185323.jpg",
    "date": "2015-07-05T17:53:26.000Z",
    "location": {
      "lat": 41.5196263888889,
      "lng": -8.78613305555556
    },
    "locationName": "Apúlia e Fão, Braga, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/432"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/df0d6e50-dd3d-4153-b1ae-dc77466fae19.jpg",
    "alt": "IMG_20150621_190000.jpg",
    "date": "2015-06-21T18:00:09.000Z",
    "location": {
      "lat": 41.6997938888889,
      "lng": -8.03698638888889
    },
    "locationName": "Vieira do Minho, Braga, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1182"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/85871cae-0244-4163-bfd6-7d6866e4a7cc.jpg",
    "alt": "IMG_20150605_022158.jpg",
    "date": "2015-06-05T01:22:19.000Z",
    "location": {
      "lat": 41.1699169444444,
      "lng": -8.68379166666667
    },
    "locationName": "Nevogilde, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/106"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/e20f1f98-059b-4572-a0a3-2878e9461d35.jpg",
    "alt": "IMG_20150603_163155.jpg",
    "date": "2015-06-03T15:31:59.000Z",
    "location": {
      "lat": 40.197385,
      "lng": -8.43537166666667
    },
    "locationName": "Santa Clara, Coimbra, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 285,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/40"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/419a2c42-39f6-4187-8406-92685316bc7d.jpg",
    "alt": "IMG_20150517_162623.jpg",
    "date": "2015-05-17T15:26:23.586Z",
    "location": {
      "lat": 41.2879104444444,
      "lng": -8.61328505555556
    },
    "locationName": "Santa Maria de Avioso, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1050"
    },
    "dimensions": "3264 × 2448"
  },
  {
    "src": "../public/img/photos/1cbe3dff-a200-4dd1-b8ab-30262af432e5.jpg",
    "alt": "IMG_20150201_152021.jpg",
    "date": "2015-02-01T17:20:27.000Z",
    "location": {
      "lat": -22.9687516666667,
      "lng": -43.3874566666667
    },
    "locationName": "Barra da Tijuca, Rio de Janeiro, Brazil",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1351"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/5584edcc-9fea-41e1-af24-81b283d68c30.jpg",
    "alt": "IMG_20150201_133204.jpg",
    "date": "2015-02-01T15:32:04.904Z",
    "location": {
      "lat": -22.9431343055556,
      "lng": -43.1993064722222
    },
    "locationName": "Rio de Janeiro, Rio de Janeiro, Brazil",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/442"
    },
    "dimensions": "1920 × 1080"
  },
  {
    "src": "../public/img/photos/fdc1d28a-9612-4c1d-bb25-c46250f78272.jpg",
    "alt": "IMG_20141128_201854.jpg",
    "date": "2014-11-28T20:18:59.000Z",
    "location": {
      "lat": 41.4967777777778,
      "lng": -8.36370138888889
    },
    "locationName": "Taipas, Braga, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 580,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/21"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/e234dd18-f64f-4183-819c-4f5f52f3fd7c.jpg",
    "alt": "IMG_20141117_141953.jpg",
    "date": "2014-11-17T13:19:56.000Z",
    "location": {
      "lat": 35.9142713888889,
      "lng": 14.4978452777778
    },
    "locationName": "Sliema, Tas-Sliema, Malta",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/635"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/ea719511-d1fe-48d6-b13b-cece0b3d7c10.jpg",
    "alt": "IMG_20140927_162746.jpg",
    "date": "2014-09-27T14:27:51.000Z",
    "location": {
      "lat": 47.8096483333333,
      "lng": 13.0612486111111
    },
    "locationName": "Salzburg, Salzburg, Austria",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/2907"
    },
    "dimensions": "3200 × 2368"
  },
  {
    "src": "../public/img/photos/67aed6c6-925f-4e54-ad0e-a3b66ca96848.jpg",
    "alt": "IMG_20140824_182738.jpg",
    "date": "2014-08-24T17:27:38.000Z",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 101,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1542"
    },
    "dimensions": "3264 × 2448"
  },
  {
    "src": "../public/img/photos/945031e3-d806-41f4-b080-e96dce7e02f6.jpg",
    "alt": "IMG_20140711_153938.jpg",
    "date": "2014-07-11T14:39:42.000Z",
    "location": {
      "lat": 38.7739205555556,
      "lng": -9.09144861111111
    },
    "locationName": "Parque das Nações, Lisbon, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/1129"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/2ffb91f5-e0d3-4ea8-906f-33a637c3623b.jpg",
    "alt": "IMG_20140608_015459.jpg",
    "date": "2014-06-08T00:55:11.000Z",
    "location": {
      "lat": 41.1464077777778,
      "lng": -8.61376583333333
    },
    "locationName": "Porto, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 1089,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/10"
    },
    "dimensions": "2368 × 3200"
  },
  {
    "src": "../public/img/photos/a51dd67f-0cda-4226-bd89-10a1f9270f49.jpg",
    "alt": "IMG_20140604_225740.jpg",
    "date": "2014-06-04T21:57:40.000Z",
    "location": {
      "lat": 41.1442947222222,
      "lng": -8.61847780555556
    },
    "locationName": "Porto, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 1137,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/30"
    },
    "dimensions": "1920 × 1080"
  },
  {
    "src": "../public/img/photos/874c6106-79dd-4a3a-94fc-69bead7dbd33.jpg",
    "alt": "IMG_20140601_185708.jpg",
    "date": "2014-06-01T17:57:08.000Z",
    "location": {
      "lat": 41.1589508055556,
      "lng": -8.65685175
    },
    "locationName": "Pinheiro Manso, Porto, Portugal",
    "camera": "LGE Nexus 5",
    "techDetails": {
      "iso": 100,
      "aperture": "f/2.4",
      "focalLength": "3.97mm",
      "exposureTime": "1/822"
    },
    "dimensions": "2448 × 3264"
  }
];
